from ._verify_error import VerifyError


class VerifyUnexpectedError(VerifyError):
    """Výjimka vyvolaná při neočekávané události."""